### ISSUE TITLE
the docs is 404

### ISSUE THREAD

**Issue by thomas-void0** [jxnblk/loading#22]
see https://jxnblk.com/loading
![image](https://user-images.githubusercontent.com/48620706/204427419-15dac1ef-2ddc-4109-9c41-38110d619264.png)

**Comment by thecotne** [comment]
this works http://jxnblk.github.io/loading/

source https://github.com/jxnblk/loading/commit/d77fd9845ca14e27919803a3e8bd802737683aca

**Comment by thomas-void0** [comment]
> this works http://jxnblk.github.io/loading/
> 
> source [d77fd98](https://github.com/jxnblk/loading/commit/d77fd9845ca14e27919803a3e8bd802737683aca)

thx~
